* Literate Documentation with Emacs and Org Mode

In this repository you'll find the source material for a [[https://osem.seagl.org/conferences/seagl2023/program/proposals/952][talk]] I hope
to give at SeaGL 2023. This talk will be in much in the same spirit as
a [[https://osem.seagl.org/conferences/seagl2019/program/proposals/664][talk]] I gave in 2019, but will be updated to include some new tips
and techniques that I've learned in the intervening years.

The main file in this repository is [[https://gitlab.com/spudlyo/orgdemo2/-/raw/main/buildemacs.org?ref_type=heads][buildemacs.org]], I've linked to the
raw version of the file in GitLab because it uses some fairly advanced
Org-mode syntax that doesn't quite render perfectly in the UI.

This file is the literate document that I'll be discussing at the
talk. The exported document itself is a relatively simple guide on how
to build GNU Emacs from scratch. What makes it interesting is that
with a few changes the document can be configured to give instructions
on how to build Emacs on either RedHat or Debian based GNU/Linux
systems.

Throughout the document I do my best to not hardcode anything that
appears in the output if any org-babel code blocks and try to keep
everything as dynamic as possible.

The document has two distinct audiences, the first of which are people
who want to learn techniques for creating literate org-mode
documents. The second is folks who want to learn techniques for building
GNU Emacs on either RedHat or Debian based distributions.

The first audience is served by reading the non-exported material in the
org mode document, and the second is intended to read the exported
document(s) which are all about building Emacs from source.
